# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # split65
  - board: seeeduino_xiao_ble
    shield: quef_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: quef_right nice_oled
    snippet: studio-rpc-usb-uart
  # split65 END
  # RESET
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: nice_nano_v2
    shield: settings_reset
  # RESET END
  # lumberjack
  - board: nice_nano_v2
    shield: lumberjack_pro
    snippet: studio-rpc-usb-uart
# lumberjack END
